version: "1.0"

services:
  frontend:
    build:
      context: ./client
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - appnetwork

  backend:
    build:
      context: ./server
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
