name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "server/**"
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          cd server
          pip install -r requirements.txt
      - name: Lint
        run: cd server && black .
        #  && flake8 .
      - name: Test
        run: cd server && pytest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    needs: [build]
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_deployment: false
          deployment_environment: "production" # e.g., production, staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
