name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "client/**"
  pull_request:
    branches: [main]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: cd client && npm install
      - name: Lint
        run: cd client && npm run lint
      - name: Test
        run: cd client && npm run test
      - name: Build
        run: cd client && npm run build
  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    needs: [build]
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_CLIENT_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_deployment: false
          deployment_environment: "production" # e.g., production, staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
